### ISSUE TITLE
Remove `bundle install` from instructions.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/rails-api-many-to-many#2]
In fact, remove all of these things:

```
Install dependencies with bundle install.
Add secrets to config/secrets.yml.
Create a database with bundle exec rake db:create.
Create a database schema with bundle exec rake db:migrate.
Run the HTTP server with bundle exec rails server.
```

**Comment by neugierige** [comment]
@payne-chris-r: ok to close?

**Comment by gaand** [comment]
Why?  Please motivate changes when possible.  I think I know, but the issue should inform.

**Comment by jrhorn424** [comment]
> the issue should inform.

cc @payne-chris-r 

Anywho, these are covered in the `rails-api-*-<demo|code-along|lab>` for now.
