### ISSUE TITLE
Add text data for example.rb file?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/rails-api-many-to-many#3]
I think if we add data for example.rb file we could start everyone on the same page with the same data...

**Comment by neugierige** [comment]
@payne-chris-r I assume you are referring to either the demo's or the code-along's `example.rb` file. Which one exactly?

**Comment by jrhorn424** [comment]
Did you mean `db/examples.rb`? I'm confused @payne-chris-r.

**Comment by jrhorn424** [comment]
Unclear. @tvlangley suggests the originally intent was partially addressed. Please open a better issue for remaining changes.

**Comment by payne-chris-r** [comment]
This was in reference to an issue on one-to-many that I dumped example data.
